name: Run traffic report

on:
  schedule:
    - cron: '* 2 * * *' # Run at 2AM
    - cron: '* 9 * * *' # Run at 9AM
    - cron: '* 13 * * *' # Run at 1PM
    - cron: '* 21 * * *' # Run at 9PM

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn install --frozen-lockfile
      - run: yarn start
      - run: yarn commit-file